server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /assets/ {
        try_files $uri =404;
        expires 7d;
        access_log off;
    }

    location = /favicon.ico {
        try_files $uri =404;
        access_log off;
    }

    # React Router 的前端路由回退到 index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
